const META = {
  apple:['תפוח','🍎','I see an apple.','a'], ant:['נמלה','🐜','The ant is small.','a'], ball:['כדור','⚽','This is a ball.','b'],
  cat:['חתול','🐱','The cat is small.','c'], sun:['שמש','☀️','The sun is hot.','s'], top:['סביבון','🪀','The top can spin.','t'],
  pen:['עט','🖊️','This is a blue pen.','p'], pig:['חזיר','🐷','The pig is pink.','p'], ink:['דיו','🖋️','The ink is black.','i'],
  net:['רשת','🥅','The net is big.','n'], sat:['ישב','🪑','The cat sat.','s'], pin:['סיכה','📌','This is a pin.','p'],
  tap:['ברז','🚰','Turn off the tap.','t'], pat:['לטפוח','🫳','Pat the dog.','p'], pan:['מחבת','🍳','The pan is hot.','p'],
  sit:['לשבת','🪑','Sit on the chair.','s'], tip:['קצה','✏️','The pencil has a tip.','t'], tin:['קופסת פח','🥫','The tin is small.','t'],
  map:['מפה','🗺️','This is a map.','m'], moon:['ירח','🌙','The moon is bright.','m'], nose:['אף','👃','This is my nose.','n'],
  dog:['כלב','🐶','The dog can run.','d'], duck:['ברווז','🦆','The duck can swim.','d'], goat:['עז','🐐','The goat is white.','g'],
  game:['משחק','🎮','This is a fun game.','g'], man:['איש','👨','The man has a hat.','m'], mat:['שטיחון','🧶','The cat is on the mat.','m'],
  nap:['תנומה','😴','I take a nap.','n'], nod:['להנהן','🙂','Nod your head.','n'], dig:['לחפור','⛏️','The dog can dig.','d'],
  gap:['רווח','↔️','There is a gap.','g'], gum:['מסטיק','🫧','The gum is pink.','g'], mug:['ספל','☕','This is my mug.','m'],
  cup:['כוס','🥤','The cup is full.','c'], kid:['ילד','🧒','The kid can run.','k'], key:['מפתח','🔑','This is a key.','k'],
  egg:['ביצה','🥚','The egg is white.','e'], elf:['שדון','🧝','The elf is small.','e'], red:['אדום','🔴','The ball is red.','r'],
  run:['לרוץ','🏃','I can run.','r'], hen:['תרנגולת','🐔','The hen has an egg.','h'], bed:['מיטה','🛏️','The bed is soft.','b'],
  leg:['רגל','🦵','This is my leg.','l'], lip:['שפה','👄','Touch your lip.','l'], rug:['שטיח','🧶','The rug is red.','r']
};

const COLORS=['#FFF0F6','#E8F7FF','#FFF8D9','#E9FFF3','#F2EDFF','#FFF0E6'];
const escapeXml = text => String(text).replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
function imageFor(word) {
  const [translation, emoji] = META[word] || [word,'🔤'];
  const color = COLORS[Math.abs([...word].reduce((sum,c)=>sum+c.charCodeAt(0),0)) % COLORS.length];
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420" viewBox="0 0 640 420" role="img" aria-label="${escapeXml(word)}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${color}"/><stop offset="1" stop-color="#fff"/></linearGradient></defs><rect width="640" height="420" rx="38" fill="url(#g)"/><circle cx="320" cy="172" r="122" fill="#fff"/><text x="320" y="218" text-anchor="middle" font-size="138" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">${emoji}</text><rect x="118" y="312" width="404" height="76" rx="30" fill="#fff"/><text x="320" y="350" text-anchor="middle" font-size="34" font-weight="800" font-family="Arial,sans-serif" fill="#253047">${escapeXml(word)}</text><text x="320" y="379" text-anchor="middle" font-size="20" font-family="Arial,sans-serif" fill="#687387" direction="rtl">${escapeXml(translation)}</text></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}
function wordObj(lessonId,index,word){const [translation,,exampleSentence,targetSound]=META[word];return {id:`${lessonId}-word-${index+1}`,word,translation,image:imageFor(word),audio:'',exampleSentence,targetSound,difficulty:1,topic:'starter',specialWord:false};}
function letter(upper,soundHe,word){return {upper,lower:upper.toLowerCase(),soundHe,exampleWord:word,translation:META[word][0],image:imageFor(word),audio:word};}
function act(id,type,instruction,extra={}){return {id,type,instruction,points:20,maxAttempts:3,correctFeedback:'כל הכבוד! הצלחתם.',retryFeedback:'כמעט! הקשיבו שוב ונסו תשובה אחרת.',...extra};}
function gallery(id,words){return act(id,'word-gallery','מכירים את המילים: לחצו על הרמקול ושמעו כל מילה',{points:10,words:words.map(word=>({word,translation:META[word][0],image:imageFor(word),audio:''}))});}
function intro(id,title,letters){return act(id,'letter-intro',title,{points:10,letters});}
function base(order,titleHe,titleEn,learningGoal,rule,words,activities,letterFocus,achievement){const id=`lesson-${String(order).padStart(3,'0')}`;return {id,order,titleHe,titleEn,stage:1,difficulty:1,icon:titleHe.includes('הגיית')?'🔤':'📖',color:['#6c5ce7','#00b894','#fd79a8','#0984e3','#f39c12','#00a8a8'][order-1],learningGoal,childInstruction:'מקשיבים, מסתכלים בתמונה, אומרים בקול ומשחקים.',parentExplanation:learningGoal,rule,letterFocus,contentStatus:'complete',words:words.map((word,index)=>wordObj(id,index,word)),activities,review:[words[0],words[1]],completionRules:{minimumActivities:5,minimumScore:60},rewards:{stars:3,points:120,sticker:`starter-${order}`,achievement},reviewWords:words.slice(0,4),commonMistakes:['בלבול בין שם האות לצליל שלה','ניחוש לפי התמונה בלי להקשיב לצליל'],exceptionsExplanation:''};}

const ABC=[letter('A','אַ קצר','apple'),letter('B','בּ','ball'),letter('C','ק / ס לפי המילה','cat')];
const SATPIN=[letter('S','ס','sun'),letter('A','אַ קצר','apple'),letter('T','ט','top'),letter('P','פּ','pen'),letter('I','אִ קצר','ink'),letter('N','נ','net')];
const MDG=[letter('M','מ','map'),letter('N','נ','nose'),letter('D','ד','dog'),letter('G','ג','goat'),letter('O','אוֹ קצר','moon')];
const CKER=[letter('C','ק','cat'),letter('K','ק','key'),letter('E','אֶ קצר','egg'),letter('R','ר','red'),letter('U','אַ קצר','cup')];

const W1=['sun','apple','ant','top','pen','pig','ink','net'];
const A1=[intro('lesson-001-a1','מתחילים מההתחלה: מכירים את A a, B b, C c',ABC),intro('lesson-001-a2','צלילי הקריאה הראשונים: S A T P I N',SATPIN),gallery('lesson-001-a3',W1),act('lesson-001-a4','letter-trace','עברו עם האצבע על האות A',{letter:'A',lower:'a',audio:'A',points:10}),act('lesson-001-a5','audio-match','הקשיבו ובחרו את המילה ששמעתם',{prompt:'sun',answer:'sun',options:['sun','top','pen','net'],audio:'sun'}),act('lesson-001-a6','image-match','איזו מילה מתאימה לתמונה?',{prompt:'apple',answer:'apple',options:['apple','ant','pig','pen'],image:imageFor('apple')}),act('lesson-001-a7','case-match','התאימו אות גדולה לאות קטנה',{prompt:'A',answer:'a',options:['a','b','c','s']}),act('lesson-001-a8','missing-letter','השלימו את האות החסרה',{prompt:'p_n',answer:'e',word:'pen',options:['e','a','i','o']}),act('lesson-001-a9','word-builder','בנו את המילה לפי הסדר',{prompt:'sun',answer:'sun',letters:['s','u','n'],audio:'sun',points:30,maxAttempts:4}),act('lesson-001-a10','memory-game','מצאו זוגות של מילה ותרגום',{pairs:[['sun','שמש'],['apple','תפוח'],['pen','עט'],['net','רשת']],points:30}),act('lesson-001-a11','pronunciation-practice','הקשיבו, אמרו והקליטו את המילה',{prompt:'apple',audio:'apple'})];
const W2=['sat','pin','tap','pat','pan','sit','tip','tin'];
const A2=[gallery('lesson-002-a1',W2),act('lesson-002-a2','audio-match','הקשיבו ובחרו את המילה',{prompt:'pin',answer:'pin',options:['pin','pan','tap','tin'],audio:'pin'}),act('lesson-002-a3','image-match','בחרו את המילה שמתאימה לתמונה',{prompt:'pan',answer:'pan',options:['pan','pin','sit','tip'],image:imageFor('pan')}),act('lesson-002-a4','multiple-choice','מה פירוש המילה?',{prompt:'tap',answer:'ברז',options:['ברז','סיכה','מחבת','קצה']}),act('lesson-002-a5','missing-letter','השלימו את האות החסרה',{prompt:'s_t',answer:'i',word:'sit',options:['i','a','e','o']}),act('lesson-002-a6','word-builder','בנו את המילה',{prompt:'pin',answer:'pin',letters:['p','i','n'],audio:'pin',points:30}),act('lesson-002-a7','memory-game','מצאו זוגות של מילה ותמונה',{pairs:[['pin','📌'],['tap','🚰'],['pan','🍳'],['tin','🥫']],points:30}),act('lesson-002-a8','pronunciation-practice','אמרו והקליטו את המילה',{prompt:'sit',audio:'sit'})];
const W3=['map','moon','net','nose','dog','duck','goat','game'];
const A3=[intro('lesson-003-a1','מכירים צלילים חדשים: M N D G O',MDG),gallery('lesson-003-a2',W3),act('lesson-003-a3','letter-trace','עברו עם האצבע על האות M',{letter:'M',lower:'m',audio:'M',points:10}),act('lesson-003-a4','audio-match','הקשיבו ובחרו את המילה',{prompt:'dog',answer:'dog',options:['dog','duck','goat','map'],audio:'dog'}),act('lesson-003-a5','image-match','איזו מילה מתאימה לתמונה?',{prompt:'moon',answer:'moon',options:['moon','nose','map','net'],image:imageFor('moon')}),act('lesson-003-a6','case-match','התאימו אות גדולה לקטנה',{prompt:'M',answer:'m',options:['m','n','d','g']}),act('lesson-003-a7','missing-letter','השלימו את האות החסרה',{prompt:'d_g',answer:'o',word:'dog',options:['o','a','i','u']}),act('lesson-003-a8','word-builder','בנו את המילה',{prompt:'map',answer:'map',letters:['m','a','p'],audio:'map',points:30}),act('lesson-003-a9','memory-game','מצאו זוגות',{pairs:[['dog','כלב'],['duck','ברווז'],['goat','עז'],['moon','ירח']],points:30}),act('lesson-003-a10','pronunciation-practice','אמרו והקליטו את המילה',{prompt:'dog',audio:'dog'})];
const W4=['man','mat','nap','nod','dig','gap','gum','mug'];
const A4=[gallery('lesson-004-a1',W4),act('lesson-004-a2','audio-match','הקשיבו ובחרו את המילה',{prompt:'mug',answer:'mug',options:['mug','gum','gap','mat'],audio:'mug'}),act('lesson-004-a3','image-match','בחרו את המילה לתמונה',{prompt:'mat',answer:'mat',options:['mat','man','nap','nod'],image:imageFor('mat')}),act('lesson-004-a4','multiple-choice','מה פירוש המילה?',{prompt:'dig',answer:'לחפור',options:['לחפור','לנוח','להנהן','ספל']}),act('lesson-004-a5','missing-letter','השלימו את האות החסרה',{prompt:'m_g',answer:'u',word:'mug',options:['u','a','e','i']}),act('lesson-004-a6','word-builder','בנו את המילה',{prompt:'man',answer:'man',letters:['m','a','n'],audio:'man',points:30}),act('lesson-004-a7','memory-game','מצאו זוגות',{pairs:[['man','איש'],['nap','תנומה'],['gum','מסטיק'],['mug','ספל']],points:30}),act('lesson-004-a8','pronunciation-practice','אמרו והקליטו את המילה',{prompt:'mug',audio:'mug'})];
const W5=['cat','cup','kid','key','egg','elf','red','run'];
const A5=[intro('lesson-005-a1','מכירים צלילים חדשים: C K E R U',CKER),gallery('lesson-005-a2',W5),act('lesson-005-a3','letter-trace','עברו עם האצבע על האות E',{letter:'E',lower:'e',audio:'E',points:10}),act('lesson-005-a4','audio-match','הקשיבו ובחרו את המילה',{prompt:'key',answer:'key',options:['key','kid','cat','cup'],audio:'key'}),act('lesson-005-a5','image-match','בחרו את המילה לתמונה',{prompt:'egg',answer:'egg',options:['egg','elf','red','run'],image:imageFor('egg')}),act('lesson-005-a6','case-match','התאימו אות גדולה לקטנה',{prompt:'E',answer:'e',options:['e','c','k','r']}),act('lesson-005-a7','missing-letter','השלימו את האות החסרה',{prompt:'r_d',answer:'e',word:'red',options:['e','a','i','u']}),act('lesson-005-a8','word-builder','בנו את המילה',{prompt:'cat',answer:'cat',letters:['c','a','t'],audio:'cat',points:30}),act('lesson-005-a9','memory-game','מצאו זוגות',{pairs:[['cat','חתול'],['key','מפתח'],['egg','ביצה'],['red','אדום']],points:30}),act('lesson-005-a10','pronunciation-practice','אמרו והקליטו את המילה',{prompt:'cat',audio:'cat'})];
const W6=['hen','bed','red','leg','kid','lip','rug','sun'];
const A6=[gallery('lesson-006-a1',W6),act('lesson-006-a2','audio-match','הקשיבו ובחרו את המילה',{prompt:'hen',answer:'hen',options:['hen','bed','leg','kid'],audio:'hen'}),act('lesson-006-a3','image-match','בחרו את המילה לתמונה',{prompt:'bed',answer:'bed',options:['bed','red','rug','sun'],image:imageFor('bed')}),act('lesson-006-a4','multiple-choice','מה פירוש המילה?',{prompt:'leg',answer:'רגל',options:['רגל','מיטה','שפה','שטיח']}),act('lesson-006-a5','missing-letter','השלימו את האות החסרה',{prompt:'l_p',answer:'i',word:'lip',options:['i','e','a','o']}),act('lesson-006-a6','word-builder','בנו את המילה',{prompt:'hen',answer:'hen',letters:['h','e','n'],audio:'hen',points:30}),act('lesson-006-a7','memory-game','מצאו זוגות',{pairs:[['hen','תרנגולת'],['bed','מיטה'],['leg','רגל'],['rug','שטיח']],points:30}),act('lesson-006-a8','pronunciation-practice','אמרו והקליטו את המילה',{prompt:'hen',audio:'hen'})];

export const starterLessons=[
  base(1,'הגיית אותיות #1','Letter Sounds #1','היכרות ראשונה עם A, B, C ולאחר מכן עם צלילי S, A, T, P, I, N.','לכל אות יש שם ולרוב גם צליל קצר שמשמש לקריאה.',W1,A1,SATPIN,'התחלתי מהאותיות'),
  base(2,'קריאת מילים #1','Reading Words #1','חיבור הצלילים הראשונים למילים קצרות בנות שלוש אותיות.','אומרים כל צליל בנפרד ואז מחברים למילה אחת.',W2,A2,SATPIN,'קורא מילים ראשון'),
  base(3,'הגיית אותיות #2','Letter Sounds #2','לימוד צלילי M, N, D, G, O באמצעות תמונות ומילים מוכרות.','מקשיבים לצליל הפותח ומקשרים אותו לאות.',W3,A3,MDG,'חוקר צלילים'),
  base(4,'קריאת מילים #2','Reading Words #2','קריאת מילים קצרות באמצעות הצלילים שכבר נלמדו.','מחברים שלושה צלילים לפי הסדר בלי לנחש לפי התמונה.',W4,A4,MDG,'קורא מילים מתקדם'),
  base(5,'הגיית אותיות #3','Letter Sounds #3','לימוד צלילי C, K, E, R, U והבחנה בין אות גדולה לקטנה.','C ו־K עשויות להשמיע צליל דומה במילים שונות.',W5,A5,CKER,'אלוף אותיות'),
  base(6,'קריאת מילים #3','Reading Words #3','תרגול קריאה, האזנה והגייה של מילים קצרות נוספות.','קוראים משמאל לימין, מחברים צלילים ובודקים מול התמונה.',W6,A6,CKER,'קורא מתחיל')
];
